### ISSUE TITLE
How to compile fro *.au3

### ISSUE THREAD

**Issue by miikael** [sinky/html5-screensaver-node-webkit#3]
Hi,

Im trying to build the screensaver from my own application and would like to compile the *.au3 for my own project. Which tool did you use for that.

Thank you,
Mihkel

**Comment by mitselek** [comment]
+1

**Comment by mitselek** [comment]
:+1:, too :)

**Comment by sinky** [comment]
Uh, didn't see this Issue.
It's an Autoit File: www.autoitscript.com
