### ISSUE TITLE
how to use screen.exe or screen.scr

### ISSUE THREAD

**Issue by cah-mike-welch** [sinky/html5-screensaver-node-webkit#4]
When I try to run screen.exe from the command prompt, nothing happens.  If I try to rename it as screen.scr, I'm able to install the screen saver.  But when I click on "Preview", once again, nothing happens.  Do I need to install Autoit in order to use screen.exe?

**Comment by thomet** [comment]
Try to download nwjs (https://github.com/nwjs/nw.js/releases) and rename the folder to `nwjs` and move it into the same folder where the exe or scr file is located. (You also need the `screen.nw` in the same folder)

Structure should like this:

folder-where-youscreensaver-should-be-located:
|- screen.nw/
|- nwjs/
|- screen.exe or screen.scr

**Comment by sinky** [comment]
Added this info to readme 6cafdefd5bb070d99666583e5fa18d36db82d35e

**Comment by sinky** [comment]
I completely overhauled the readme. And gave the NEW windows screensaver executable a own repository.
